name: CI

on:
  push:
    branches:
      - hexo

env:
  GIT_USER: Misaka13514
  GIT_EMAIL: Misaka13514@gmail.com
  THEME_REPO: Misaka13514/hexo-theme-next
  THEME_BRANCH: master
  DEPLOY_REPO: Misaka13514/Misaka13514.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: macOS-latest
    strategy:
      matrix:
        os: [macOS-latest]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/next

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo mv /etc/localtime  /etc/localtime-old
          sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew install pandoc
          brew install pandoc-citeproc
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          cp _config.theme.yml themes/next/_config.yml
          git clone https://github.com/Misaka13514/i.moeneko.xyz.git ./about
          mkdir public
          mkdir public/about
          cd ./about
          npm install .
          npm run build
          cp -r ./dist/* ../public/about/
          cd ..

      - name: Install dependencies
        run: |
          npm install
          npm install -g hexo-cli

      - name: Deploy hexo
        run: |
          hexo g
          npm run deploy
