name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  GIT_USER:      ${{secrets.GIT_USER}}
  GIT_EMAIL:     ${{secrets.GIT_EMAIL}}
  DEPLOY_REPO:   ${{secrets.DEPLOY_REPO}}
  DEPLOY_PRI:    ${{secrets.DEPLOY_PRI}}
  DEPLOY_BRANCH: gh-pages

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: True

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        run: |
          ./env_config.sh
          mkdir -p ~/.ssh/
          echo "${{ env.DEPLOY_PRI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name  ${{ env.GIT_USER }}
          git config --global user.email ${{ env.GIT_EMAIL }}

      - name: Install dependencies
        run: |
          yarn

      - name: Build hexo pages
        run: |
          yarn run build

      - name: replace new page
        run: |
          rm -rf .deploy_git/*
          cp -r public/* .deploy_git/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: .deploy_git
          CLEAN: true